name: ryanmoore
favicon: null
layout_spectrum: 0.1285174093209207
typography_spectrum: 0.19468972459435463
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.23998717754147947
  lightness: 0.8023682765197009
  saturation: 0.7640214911662042
  rhythmicContrast: 0.277193998452276
purpose: []
